"""
Document management service.
Handles S3 integration, file validation, and presigned URLs.
"""

import hashlib
from typing import Tuple
from datetime import datetime, timedelta

from app.config import get_settings

# Allowed file types
ALLOWED_FILE_TYPES = {
    "application/pdf": ".pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
    "application/vnd.ms-word.document.macroEnabled.12": ".docm",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
    "application/vnd.ms-excel.sheet.macroEnabled.12": ".xlsm",
    "image/jpeg": ".jpg",
    "image/png": ".png",
}

MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB


def validate_document_file(
    file_name: str,
    file_size: int,
    file_type: str,
) -> None:
    """
    Validate document file before upload.
    Checks file type and size.
    """
    # Check file size
    if file_size > MAX_FILE_SIZE:
        raise ValueError(f"File size exceeds maximum of {MAX_FILE_SIZE // 1024 // 1024}MB")

    # Check file type
    if file_type not in ALLOWED_FILE_TYPES:
        allowed = ", ".join(ALLOWED_FILE_TYPES.values())
        raise ValueError(f"File type not allowed. Allowed: {allowed}")

    # Check file extension matches content type
    file_ext = "." + file_name.split(".")[-1].lower() if "." in file_name else ""
    if file_ext and file_ext not in ALLOWED_FILE_TYPES.values():
        raise ValueError("File extension does not match allowed types")


def calculate_file_hash(file_content: bytes) -> str:
    """
    Calculate SHA-256 hash of file content.
    """
    return hashlib.sha256(file_content).hexdigest()


async def generate_presigned_upload_url(
    document_id: str,
    file_name: str,
    file_type: str,
    law_firm_id: str,
) -> Tuple[str, str]:
    """
    Generate presigned S3 upload URL.
    Returns (presigned_url, s3_key).

    In a real implementation, this would use boto3 to interact with S3.
    For now, returns mock URLs.
    """
    settings = get_settings()

    # S3 key format: law_firm_id/year/month/document_id_filename
    now = datetime.utcnow()
    s3_key = f"{law_firm_id}/{now.year}/{now.month:02d}/{document_id}_{file_name}"

    # Mock presigned URL (would be generated by boto3 in production)
    # In real implementation:
    # s3_client = boto3.client('s3')
    # presigned_url = s3_client.generate_presigned_post(
    #     Bucket=settings.s3_bucket,
    #     Key=s3_key,
    #     ExpiresIn=3600,
    #     Conditions=[
    #         {'Content-Type': file_type},
    #         ['content-length-range', 0, MAX_FILE_SIZE],
    #     ]
    # )

    # Mock response for development
    presigned_url = (
        f"https://{settings.s3_bucket}.s3.amazonaws.com/{s3_key}?"
        f"X-Amz-Signature=MOCK&X-Amz-Date={now.isoformat()}"
    )

    return presigned_url, s3_key


async def generate_presigned_download_url(s3_key: str) -> str:
    """
    Generate presigned S3 download URL.
    Client uses this URL to download the file directly from S3.
    """
    settings = get_settings()

    # Mock presigned URL (would be generated by boto3 in production)
    # In real implementation:
    # s3_client = boto3.client('s3')
    # presigned_url = s3_client.generate_presigned_url(
    #     'get_object',
    #     Params={'Bucket': settings.s3_bucket, 'Key': s3_key},
    #     ExpiresIn=3600,
    # )

    now = datetime.utcnow()
    presigned_url = (
        f"https://{settings.s3_bucket}.s3.amazonaws.com/{s3_key}?"
        f"X-Amz-Signature=MOCK&X-Amz-Date={now.isoformat()}"
    )

    return presigned_url


async def delete_document_from_s3(s3_key: str) -> None:
    """
    Delete document from S3.
    Called when document is permanently deleted.
    """
    # In real implementation:
    # s3_client = boto3.client('s3')
    # s3_client.delete_object(Bucket=settings.s3_bucket, Key=s3_key)
    pass
